title:             Programando Dados
email:             programando.dados@gmail.com
description:       Reflexões sobre programação e ciência de dados
author:            Rodrigo Ângelo
baseurl:           "/"
url:               "http://rodrigoangelo.net.br"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
